IF DB_ID('GAMES_SALES_PLATFORM') IS NOT NULL
	BEGIN
		ALTER DATABASE [GAMES_SALES_PLATFORM] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
		USE master
		DROP DATABASE GAMES_SALES_PLATFORM
	END
GO

CREATE DATABASE GAMES_SALES_PLATFORM
	ON PRIMARY	(
					NAME = 'GAMES_SALES_PLATFORM_DB',
					FILENAME = 'C:\database\GAMES_SALES_PLATFORM.mdf',
					SIZE = 5MB,
					MAXSIZE = 100MB,
					FILEGROWTH = 5MB
				)
	LOG ON		(
					NAME = 'GAMES_SALES_PLATFORM_DB_LOG',
					FILENAME = 'C:\database\GAMES_SALES_PLATFORM.ldf',
					SIZE = 2MB,
					MAXSIZE = 50MB,
					FILEGROWTH = 1MB
				)
GO

USE GAMES_SALES_PLATFORM

CREATE TABLE KULLANICI
(
	KULLANICI_ID INT NOT NULL PRIMARY KEY,
	ADI VARCHAR(30),
	EMAIL VARCHAR(50)
)
GO

CREATE TABLE YAYIMCI
(
	YAYIMCI_ID INT NOT NULL PRIMARY KEY,
	EMAIL VARCHAR(50),
	ADI VARCHAR(30),
	KURULUS_TARIHI DATE,
	WEBSITE VARCHAR(50)
)
GO

CREATE TABLE YAPIMCI
(
	YAPIMCI_ID INT NOT NULL PRIMARY KEY,
	EMAIL VARCHAR(50),
	ADI VARCHAR(30),
	KURULUS_TARIHI DATE,
	WEBSITE VARCHAR(50)
)
GO

CREATE TABLE BUNDLE
(
	BUNDLE_ID INT NOT NULL PRIMARY KEY,
	ADI VARCHAR(30),
	FIYAT SMALLMONEY
)
GO

CREATE TABLE OYUN
(
	OYUN_ID INT NOT NULL PRIMARY KEY,
	ADI VARCHAR(30),
	BUNDLE_ID INT FOREIGN KEY REFERENCES BUNDLE(BUNDLE_ID),
	YAPIMCI_ID INT FOREIGN KEY REFERENCES YAPIMCI(YAPIMCI_ID),
	YAYIMCI_ID INT FOREIGN KEY REFERENCES YAYIMCI(YAYIMCI_ID)
)
GO

CREATE TABLE ODEMETURU
(
	ODEME_ID INT NOT NULL PRIMARY KEY,
	ADI VARCHAR(30),
)
GO

CREATE TABLE TAHSILAT
(
	TAHSILAT_ID INT NOT NULL PRIMARY KEY,

	/* OPSIYONEL */
	KULLANICI_ADI VARCHAR(30),
	SON_KULLANMA_TARIHI DATE NOT NULL,
	GUVENLIK_KODU INT NOT NULL,
	KART_NO INT NOT NULL,
	/* OPSIYONEL */
	ODEME_ID INT FOREIGN KEY REFERENCES ODEMETURU(ODEME_ID)
)
GO

CREATE TABLE FATURA
(
	FATURA_NO INT FOREIGN KEY REFERENCES TAHSILAT(TAHSILAT_ID),
	TUTAR SMALLMONEY,
	TARIH DATE,
	ODEME_ID INT FOREIGN KEY REFERENCES ODEMETURU(ODEME_ID),
	PRIMARY KEY(FATURA_NO)
)
GO

CREATE TABLE ANAHTAR
(
	ANAHTAR_ID INT NOT NULL PRIMARY KEY,
	FIYAT SMALLMONEY,
	KULLANICI_ID INT FOREIGN KEY REFERENCES KULLANICI(KULLANICI_ID),
	OYUN_ID INT FOREIGN KEY REFERENCES OYUN(OYUN_ID),
	FATURA_NO INT FOREIGN KEY REFERENCES FATURA(FATURA_NO)
)
GO

CREATE TABLE BASARIMLAR
(
	BASARIM_ID INT NOT NULL PRIMARY KEY,
	ADI VARCHAR(30),
	OYUN_ID INT FOREIGN KEY REFERENCES OYUN(OYUN_ID)
)
GO

/*DROP TABLE #KAZANIR*/
CREATE TABLE KAZANIR
(
	KULLANICI_ID INT FOREIGN KEY REFERENCES KULLANICI(KULLANICI_ID),
	BASARIM_ID INT FOREIGN KEY REFERENCES BASARIMLAR(BASARIM_ID),
	PRIMARY KEY(KULLANICI_ID, BASARIM_ID)
)
GO

/*DROP TABLE #YORUMYAPAR*/
CREATE TABLE YORUMYAPAR
(
	YORUM_ID INT NOT NULL,
	METIN VARCHAR(100),
	BEGEN INT,
	BEGENMEME INT,
	KULLANICI_ID INT FOREIGN KEY REFERENCES KULLANICI(KULLANICI_ID),
	OYUN_ID INT FOREIGN KEY REFERENCES OYUN(OYUN_ID),
	PRIMARY KEY(YORUM_ID, KULLANICI_ID, OYUN_ID)
)
GO

CREATE TABLE ODULLER
(
	ODUL_ID INT NOT NULL PRIMARY KEY,
	ADI VARCHAR(30),
	TARIH DATE,
	OYUN_ID INT FOREIGN KEY REFERENCES OYUN(OYUN_ID)
)
GO

CREATE TABLE KATEGORILER
(
	KATEGORI_ID INT NOT NULL PRIMARY KEY,
	ADI VARCHAR(30),
	TUR VARCHAR(30)
)
GO

/*DROP TABLE #ICERIR*/
CREATE TABLE ICERIR
(
	OYUN_ID INT FOREIGN KEY REFERENCES OYUN(OYUN_ID),
	KATEGORI_ID INT FOREIGN KEY REFERENCES KATEGORILER(KATEGORI_ID),
	PRIMARY KEY(OYUN_ID, KATEGORI_ID)
)
GO